### ISSUE TITLE
Place to share transformations

### ISSUE THREAD

**Issue by apohllo** [solnic/transproc#102]
I assume that people using Transproc invent similar transformations that are not part of the library. I don't think that all (or any) such transformations should get into the library, since I think it's good that it's small. But on the other hand it would be helpful if there was a place to share these transformations - in order to learn, share and discuss the way people use Transproc.

@solnic do you think it's a good idea? Maybe the wiki would be a good place for that?

**Comment by solnic** [comment]
Starting a wiki seems like a good starting point

**Comment by apohllo** [comment]
Cool, I have already written some examples https://github.com/solnic/transproc/wiki
