### ISSUE TITLE
Transproc::Coercions to_datetime

### ISSUE THREAD

**Issue by maierru** [solnic/transproc#103]
module T
  extend Transproc::Registry
  import Transproc::Coercions
end

> T[:to_datetime]["' OR '1'='1"]
=> #<DateTime: 2001-01-01T00:00:00+00:00 ((2451911j,0s,0n),+0s,2299161j)>

http://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/DateTime.html#method-c-parse
"....This method does not function as a validator..."

**Comment by solnic** [comment]
It's not transproc's job to validate input. Closing.
