### ISSUE TITLE
bigdecimal dependency missing ?

### ISSUE THREAD

**Issue by bilby91** [solnic/transproc#104]
I started using `transproc` in a new project and it failed because `bigdecimal` dependency was missing, had to manually add it to my gemspec. Shouldn't this be a hard dependency ?

**Comment by v-kolesnikov** [comment]
Hi, @bilby91 !
What do you mean by "dependency"? `BigDecimal` is a part of Ruby standard library https://ruby-doc.org/stdlib/libdoc/bigdecimal/rdoc/index.html So, we can use `BigDecimal` in any Ruby environment without defining it in gemspec. Could you show a minimal representation script to demonstrate the problem?

**Comment by bilby91** [comment]
That was my first thought. Then I found this that explained my issue => https://github.com/solnic/transproc/blob/master/lib/transproc/coercions.rb#L3

Make sense ? 

Thanks!!

**Comment by v-kolesnikov** [comment]
Yes. It [_requires_](https://ruby-doc.org/core-2.5.3/Kernel.html#method-i-require) `bigdecimal.rb` file from the standard Ruby library. But is does not mean that `bigdecimal` must be a hard dependency.

**Comment by bilby91** [comment]
Will try to build something minimal to reproduce my problem. If I can't get that done is something on my environment messing this up for sure.

**Comment by bilby91** [comment]
At the end the Issue was related to my environment. On alpine `ruby-bigdecimal` package needs to be installed.

Thanks @v-kolesnikov
