### ISSUE TITLE
Rename keys when nesting

### ISSUE THREAD

**Issue by tomchipchase** [solnic/transproc#115]
I have a hash where I want to move some attributes into a nested object, and rename them at the same time.

I know I could rename them first, but I actually have some other top level keys that would conflict, so I have to do something like:

```
class Transformer < Transproc::Transformer
  rename_keys foo: :actual_foo
  rename_keys bar_foo: :foo 
  nest :bar, [:foo]
  rename_keys actual_foo: :foo
end

Transformer.new.call(foo: 1, bar_foo: 2)
# => { foo: 1, bar: { foo: 2 } }
```

I'd like to do this instead:
```

class Transformer < Transproc::Transformer
  nest :bar, { bar_foo: :foo }
end

Transformer.new.call(foo: 1, bar_foo: 2)
# => { foo: 1, bar: { foo: 2 } }
```

Looking at the nest method, it looks like it would be straight forward to add, but before I open a pull request, I wanted to check if this would be desirable, or if there would be a better way?

**Comment by solnic** [comment]
You can have something like `nest_and_rename` but `nest` itself shouldn't be changed to do two things.

ps. `transproc` was ported to `dry-rb/dry-transformer` so any issues will be resolved there from now on.
