### ISSUE TITLE
Add transformations for instantiating objects from input

### ISSUE THREAD

**Issue by solnic** [solnic/transproc#29]
Currently ROM does that by simply doing `t(-> tuple { header.model.new(tuple) })` but I think it'd be good to have a function for that here with a couple of strategies:

- model.new(input)
- object allocation + set ivars (this should be faster but skips the constructor)
- with splat args for struct-like constructors

I'm not sure about the naming though, in morpher there's `load_attribute_hash`, `load_attribute_accessors` and `load_instance_variables`. Maybe we should use the same but I dunno.

**Comment by AMHOL** [comment]
Initial thought on the first point:
```ruby
Transproc.register(:constructor_inject, -> (klass, *args) { klass.new(*args) })
```
I don't like the `load_*` as it isn't actually loading anything, and with `load_attribute_hash` - seems a little superfluous to assume that the argument will be a hash, maybe this stuff could go under `Transproc::Utilities` or something.

Looking back, looks like the constructor inject will handle struct instantiation as well as mass-assignment:

```ruby
User = Struct.new(:id, :name)
Transproc(:constructor_inject, User)[1, 'Peter']
```

**Comment by AMHOL** [comment]
I think sticking with inject for ivars works well too, i.e.

```ruby
Transproc.register(:inject_ivars) do |ivars, object|
  ivars.each_with_object(object) do |(key, value), obj|
    obj.instance_variable_set("@#{key}".to_sym, value)
  end
end
object = Object.new
Transproc(:inject_ivars, object)[{ test: 'tester' }]
```

**Comment by AMHOL** [comment]
Works by modifying `Transproc::Function#call` to:

```ruby
    def call(*values)
      fn[*(values + args)]
    rescue => ex
      raise MalformedInputError.new(@fn, values, ex)
    end
    alias_method :[], :call
```

**Comment by solnic** [comment]
Maybe `inject_hash`, `inject_args` and `allocate` + `set_ivars`?

**Comment by AMHOL** [comment]
Can't `inject_hash` and `inject_args` just be supported with `constructor_inject` with one or multiple arguments?

What would `allocate` be for? `set_ivars` works :smile:

**Comment by solnic** [comment]
Oh, it would `allocate` instead of `new` - the difference being the object constructor never gets called resulting in faster instantiation. If all you care about is an object with specific state then allocate + writing ivars would be enough.

**Comment by AMHOL** [comment]
Ahh OK cool, does `allocate` need to be in transproc? Could just do:

```ruby
MyClass = Class.new { attr_reader :attribute }
Transproc(:set_ivars, MyClass.allocate)[attribute: 'value']
```

**Comment by solnic** [comment]
Good point, let’s start w/o it and just pass in allocated object

**Comment by AMHOL** [comment]
@solnic can this be closed now?
