### ISSUE TITLE
Redefining transprocs

### ISSUE THREAD

**Issue by nepalez** [solnic/transproc#45]
When Transproc registers a function it [checks if its already defined and raises an error](https://github.com/solnic/transproc/blob/master/lib/transproc.rb#L21-L27). Due to this I cannot reload functions (for example `wrap`) in my module.

What is worse, even when I define a unique name `nepalez_custom_wrap` I cannot sleep well because somebody could like that awful name add add it to transproc. And this will break my code.

Wouldn't it be better to allow rewriting registered function with a new defininition?

**Comment by AMHOL** [comment]
I don't think it is a good idea to allow overrides, at least this way you're never going to get unexpected behaviour i.e. you could be expecting wrap to work the way it does now, require *insert library here* which modifies the behavior, and :boom: your app is foobar. I think namespacing is a good idea here.

**Comment by nepalez** [comment]
But what if I want slightly other behavior for the `wrap`? Well, I could create another name

The actual problem is just the same as in the Pandora's Box aka ActiveSupport. Why on earth my app functions should break if someone decided to add the same name to `transproc`?

I agree, this could be avoided if `Transproc` allowed to namespace functions. But how?
Now when I do [`extend Transproc::Functions`](https://github.com/solnic/transproc/blob/master/README.md#usage), I need to dodge all the predefined names.

**Comment by AMHOL** [comment]
Yeah, I was thinking about that too, i.e. could add a namespace option:

```ruby
module MyTransformations
  extend Transproc::Functions

  namespace :my_namespace

  def wrap(*)
    # ...
  end
end

Transproc.configure do |config|
  config.default_namespace = :my_namespace
end

Transproc(:wrap, *args)[{ ex: :ample }] # Same as Transproc(:wrap, *args, namespace: :my_namespace)[{ ex: :ample }]
```

But think that could get messy when you can just namespace with a prifix, not sure on this one, I'm sure when @solnic isn't busy he'll know what the best option is.

Was thinking the same wrt ActiveSupport :trollface: :laughing:

**Comment by solnic** [comment]
The plan is to get rid of global transproc fn namespace and create an object with function registry
