### ISSUE TITLE
Removal of global registry

### ISSUE THREAD

**Issue by nepalez** [solnic/transproc#52]
I've tried switching from `Functions` to `Registry`. Mainly there are no problems except for 2 minor issues (pp. 2-3 below).

The plan for removing global registry is this:
1. Add `compose` method to `Transproc::Registry` to exclude the necessity of `Transproc::Helper`
2. Update `Transproc::Registry` to work with classes, not only modules - to support the [specification](https://github.com/solnic/transproc/blob/master/spec/unit/composer_spec.rb#L6) where instead of `include Transproc::Composer`, the `include MyTransproc` could be used.
3. Fix `Transproc::Registry` to return a proper composed name following the [specification](https://github.com/solnic/transproc/blob/master/spec/unit/function_spec.rb#L5).
   For now it returns a `proc/lambda` instead of the name (because in absence of the True registry `Transproc::Registry` just converted module methods to procs and doesn't care of their names).
4. Write a wiki page with a description about how to move from using `Transproc::Functions` to `Transproc::Registry`
5. Add deprecation messages with a reference to wiki page to the following methods:
   - `Transproc::Functions.extended()`
   - `Transproc::Helper.included()`
   - `Transproc::Helper#t()`
   - `Transproc()` (global)
6. Bump v0.2.5
7. Update all specs and transprocs (actually I've tried it and it works) so that they use new syntax (deprecation can work fine with a mixed one).
8. Remove `Transproc::Functions`, `Transproc::Helper`, `Transproc()`
9. Change mutant settings (as I tried out in [assertion](https://github.com/nepalez/assertion) and [faceter](https://github.com/nepalez/assertion) mutant works fine with `Transproc::Registry` without any special settings)
10. Update specs to have 100% mutant coverage
11. Bump v1.0.0 (backward incompatible to v0.2)

**Comment by solnic** [comment]
wow nice, thanks for the plan.

So, after all using transproc would boil down to defining your own module, including registry extension and specifying which functions you want to have available there, right?

What about composition? In more complex cases current API is so-so to be honest. I was thinking about trying something like `t(:foo).then(t(:blah))` which is much nicer formatting-wise. We could also sneak in things like `t(:foo).maybe(t(:bar).or(t(:baz)))` too, which I believe could be really powerful.

**Comment by nepalez** [comment]
Yes, exactly. And then defining additional methods in that module. (For now I used it in 2 ways - either collect all transprocs in one gem-specific module, like in a `faceter`, or made several modules like `inflection` and `list` in `assertion`)

Concerning composition, I think (see p.1 in a plan) allowing `Transproc::Registry.compose` method can be useful, though personally I prefer chaining `:>>` (and in `#51` even thinking of `:<<`).

Whatever, various composers can be defined on `Function` just like `:>>`.

PS. What about `t(:foo).maybe(t(:just_bar)|t(:nothing))` ? ;)

**Comment by solnic** [comment]
@nepalez operators are cool for chaining but suck for formatting and readability IMO, hence I started thinking about not using operators so that things can be nicely formatted with parenthesis which should improve readability
