### ISSUE TITLE
Rename keys assumes the "from" key exists

### ISSUE THREAD

**Issue by robmiller** [solnic/transproc#64]
Hello,

I'm opening this as an issue, rather than a pull request, because I'd like to discuss approaches as much as anything else.

In the hash transformations repository there is a transformation called `rename_keys`. This does as follows, taking the hash it's passed and renaming any keys in the source hash to whatever the mapping tells it to:

``` ruby
def self.rename_keys!(hash, mapping)
  mapping.each { |k, v| hash[v] = hash.delete(k) }
  hash
end
```

However, I've run into a problem. If the hash doesn't have an element with the "from" key (`k` in the above code), `delete` will return `nil` and so the "to" value (`hash[v]`) will be set to `nil` — even if the "to" value already existed. The value will, in other words, be overwritten.

I have the scenario where I'm combining three sources of data. They all have a field that represents the same thing — a URL — but each source has a different name for it: `url`, `affiliate_url`, and `website_url`. I want to normalise these three fields to `url`, and so I hoped I could do:

``` ruby
t(:rename_keys, website_url: :url, affiliate_url: :url)
```

However, because of the previously mentioned `delete` behaviour, this results in two of the three sources of data getting clobbered and having their data overwritten with `nil`. Only one survives.

It's an easy solve; I just wrote my own transformation that runs:

``` ruby
mapping.each { |k, v| hash[v] = hash.delete(k) if hash.has_key?(k) }
```

…but I struggled to think of reasons why that shouldn't be the default behaviour. Do you have any strong thoughts/feelings about it?

**Comment by solnic** [comment]
I don't think the current behavior is correct. This transformation is meant to rename keys, that's the only thing it must do, accidentally adding new keys is a bug.

Thoughts? /cc @nepalez
