### ISSUE TITLE
Make `combine` faster

### ISSUE THREAD

**Issue by solnic** [solnic/transproc#82]
[`ArrayTransformations.combine`](https://github.com/solnic/transproc/blob/master/lib/transproc/array.rb#L144-L175) is a beast, and it's slow, so it's time to make it fast.

Refs rom-rb/rom-repository#51

**Comment by splattael** [comment]
Is this https://github.com/rom-rb/rom-repository/issues/51#issuecomment-273049284 the brenchmark I should use?

**Comment by solnic** [comment]
@splattael https://github.com/solnic/transproc/tree/perf-tweaks there's benchmarks dir with the setup I used originally, hope this helps

**Comment by splattael** [comment]
:+1: Thanks!

**Comment by solnic** [comment]
@splattael notice that I kept `combine_slow` in that branch that's why this bench actually runs :)

**Comment by splattael** [comment]
@solnic Yep, saw it. Good idea!

**Comment by solnic** [comment]
Closing, as it's multiple times faster now :) Thanks @splattael and @Kukunin for helping with this

**Comment by splattael** [comment]
Kudos to @Kukunin !! I was just too... slow 😷😅
