### ISSUE TITLE
Use Hash#transform_keys on Ruby 2.5+

### ISSUE THREAD

**Issue by flash-gordon** [solnic/transproc#97]
Transproc has `map_keys` which can use `Hash#transform_keys` starting Ruby 2.5 (see https://bugs.ruby-lang.org/issues/13583 and https://github.com/solnic/transproc/pull/96). Also, we could consider renaming this function since it's now in the lang.

**Comment by v-kolesnikov** [comment]
I would love to make PR on weekends.

**Comment by solnic** [comment]
Sounds good
